# Generated by Django 3.0.3 on 2020-03-30 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='信息标题')),
                ('message_content', models.TextField(verbose_name='信息内容')),
                ('message_status', models.CharField(choices=[('0', '未读'), ('1', '已读'), ('2', '信息')], default='0', max_length=15, verbose_name='信息状态')),
                ('send_time', models.DateField(auto_now=True, verbose_name='发送日期')),
                ('receiver', models.ManyToManyField(related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='收件人')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='发件人')),
            ],
            options={
                'verbose_name': '信息',
                'verbose_name_plural': '信息',
            },
        ),
    ]
