# Generated by Django 3.0.3 on 2020-02-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='/upload/avatar/sausages.jpg', upload_to='', verbose_name='头像'),
        ),
    ]
