# Generated by Django 3.0.3 on 2020-02-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20200226_2207'),
        ('users', '0003_auto_20200227_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_categories',
            field=models.ManyToManyField(blank=True, null=True, to='movies.Category', verbose_name='关注标题'),
        ),
    ]
