# Generated by Django 3.0.3 on 2020-03-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200228_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True, unique=True, verbose_name='邮箱'),
        ),
    ]
