# Generated by Django 3.0.3 on 2020-02-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=10, unique=True, verbose_name='类型')),
            ],
            options={
                'verbose_name': '电影类型',
                'verbose_name_plural': '电影类型',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('country', models.CharField(max_length=50, verbose_name='国籍')),
                ('desc', models.TextField(verbose_name='简介')),
                ('photo', models.ImageField(null=True, upload_to='person', verbose_name='照片')),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='影片名')),
                ('link_addr', models.CharField(max_length=100, verbose_name='链接地址')),
                ('language', models.CharField(max_length=20, verbose_name='语言')),
                ('area', models.CharField(max_length=10, verbose_name='地区')),
                ('length', models.IntegerField(verbose_name='片长(分钟)')),
                ('desc', models.TextField(verbose_name='简介')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='上映日期')),
                ('post', models.ImageField(null=True, upload_to='movie', verbose_name='电影封面')),
                ('actors', models.ManyToManyField(related_name='actors', to='movies.Person', verbose_name='演员')),
                ('directors', models.ManyToManyField(related_name='directors', to='movies.Person', verbose_name='导演')),
                ('movie_type', models.ManyToManyField(to='movies.MovieType', verbose_name='类型')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
            },
        ),
    ]
