# Generated by Django 3.0.3 on 2020-02-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='stars',
        ),
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.IntegerField(default=0, verbose_name='评分'),
        ),
    ]
