# Generated by Django 3.0.3 on 2020-02-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200225_1338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieType',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='type_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='name',
        ),
    ]
