# Generated by Django 3.0.3 on 2020-03-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20200226_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.FloatField(default=0, verbose_name='评分'),
        ),
    ]
