# Generated by Django 3.0.3 on 2020-03-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200228_1443'),
        ('movies', '0007_auto_20200302_2037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='MovieCategory',
        ),
        migrations.AddField(
            model_name='person',
            name='category',
            field=models.CharField(choices=[('0', '演员'), ('1', '导演'), ('2', '导演/演员')], default='0', max_length=10, verbose_name='人员类型'),
        ),
    ]
