# Generated by Django 3.0.3 on 2020-05-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='合辑名称')),
                ('desc', models.TextField(verbose_name='合辑简介')),
                ('post', models.ImageField(upload_to='video', verbose_name='专辑封面')),
                ('content_movies', models.ManyToManyField(to='movies.Movie', verbose_name='电影')),
            ],
            options={
                'verbose_name': '电影合辑',
                'verbose_name_plural': '电影合辑',
            },
        ),
    ]
